name: package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: install whiskers
        run: |
          cargo install catppuccin-whiskers

      - name: Generate dtx freshly
        run: |
          make whiskers

      - name: Check if whisker generated same file
        run: |
          git diff --exit-code
